export const LIVE_SITE = 'https://playbeat.live';
export const LIVE_PAGES: Record<string, { title: string; description: string; heading: string; text: string }> = {
 '/': {title:'PlayBeat Live — Watch Live TV Online', description:'Browse live TV channels on PlayBeat Live. Find news, sports and entertainment, search by category, and save your favourite channels.', heading:'Discover PlayBeat Live',text:'Explore live television in your browser. Search the channel library, browse categories and keep your favourite channels together. Available feeds and picture quality vary by channel and region.'},
 '/live-tv': {title:'Live TV Channels Online | PlayBeat Live',description:'Explore the PlayBeat Live channel library for news, sports and entertainment. Search channels, filter categories and watch available live broadcasts.',heading:'Explore live television',text:'Find a channel by name or browse the categories in the live library. Select Play to open the player. If a feed is unavailable, try another channel or return later.'},
 '/movies': {title:'Browse Movies | PlayBeat Live',description:'Explore the movie section on PlayBeat Live. Movie availability depends on the connected catalogue; check the page for current titles and availability.',heading:'Explore the movie catalogue',text:'Browse titles available through the connected movie catalogue. If no catalogue is connected, this section shows its availability status. A live cinema channel is a scheduled broadcast rather than an on-demand movie.'},
 '/series': {title:'Browse Web Series | PlayBeat Live',description:'Explore web series on PlayBeat Live. Check the connected catalogue for available shows, seasons and episodes.',heading:'Explore web series',text:'Look for shows in the connected series catalogue. Availability of seasons and episodes depends on the source. If the catalogue is unavailable, the page displays its connection status.'},
};
export function liveTab(path: string): 'live' | 'movies' | 'series' { return path === '/movies' ? 'movies' : path === '/series' ? 'series' : 'live'; }
export function escapeHtml(value: string) { return value.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!)); }
export function liveSitemap() { return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${Object.keys(LIVE_PAGES).map(path => `<url><loc>${LIVE_SITE}${path}</loc></url>`).join('')}</urlset>`; }
